[package]
license = ["Apache-2.0"]
keywords = ["Business Management/ERP", "Cost/Paid"]
org = "ballerinax"
name = "saps4hana.pp.idm"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/saps4hana.pp.idm"
version = "1.4.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
