[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Product Management", "Cost/Paid"]
org = "ballerinax"
name = "prodpad"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/prodpad"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
