[package]
license = ["Apache-2.0"]
keywords = ["AI/Images", "Vendor/Stability AI", "Cost/Paid", "Stable Diffusion"]
org = "ballerinax"
name = "stabilityai"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/stabilityai"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
