[package]
license = ["Apache-2.0"]
keywords = ["Business Management/ERP", "Cost/Paid"]
org = "ballerinax"
name = "sap.fieldglass.approval"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/sap.fieldglass.approval"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
