[package]
license = ["Apache-2.0"]
keywords = ["AI/Vector Databases", "Cost/Freemium", "Vendor/Weaviate", "Embedding Search"]
org = "ballerinax"
name = "weaviate"
icon = "icon.png"
version = "1.0.1"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/weaviate"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
