[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Marketing Automation", "Cost/Freemium"]
org = "ballerinax"
name = "sendgrid"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/sendgrid"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
