[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Geographic Information Systems", "Cost/Free"]
org = "ballerinax"
name = "earthref.fiesta"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/earthref.fiesta"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
