[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Geographic Information Systems", "Cost/Freemium"]
org = "ballerinax"
name = "iptwist"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/iptwist"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
