[package]
license = ["Apache-2.0"]
keywords = ["Support//Customer Support", "Cost/Freemium"]
org = "ballerinax"
name = "jira.servicemanagement"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/jira.servicemanagement"
version = "1.3.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
