[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Paid"]
org = "ballerinax"
name = "iris.esignature"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/iris.esignature"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
