[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Paid"]
org = "ballerinax"
name = "elasticsearch"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/elasticsearch"
version = "1.3.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
