[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Databases", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.clouddatastore"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/googleapis.clouddatastore"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
