[package]
license = ["Apache-2.0"]
keywords = ["Communication/Video Conferencing", "Cost/Paid"]
org = "ballerinax"
name = "gototraining"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/gototraining"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
