[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Video & Audio", "Cost/Free"]
org = "ballerinax"
name = "themoviedb"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/themoviedb"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
