[package]
license = ["Apache-2.0"]
keywords = ["Education/Elearning", "Cost/Paid"]
org = "ballerinax"
name = "clever.data"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/clever.data"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
