[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Contact Management", "Cost/Freemium"]
org = "ballerinax"
name = "brex.onboarding"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/brex.onboarding"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
