[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/Search Engine Optimization", "Cost/Paid"]
org = "ballerinax"
name = "botify"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/botify"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
