[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Social Media Accounts", "Cost/Freemium"]
org = "ballerinax"
name = "dev.to"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/dev.to"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
