[package]
license = ["Apache-2.0"]
keywords = ["Azure", "OpenAI", "Finetunes"]
org = "ballerinax"
name = "azure.openai.finetunes"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
