[package]
license = ["Apache-2.0"]
keywords = ["Lifestyle & Entertainment/Books", "Cost/Paid"]
org = "ballerinax"
name = "isbndb"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/isbndb"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
