[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Gateway", "Cost/Paid"]
org = "ballerinax"
name = "aayu.mftg.as2"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/aayu.mftg.as2"
version = "1.3.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
