[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Freemium"]
org = "ballerinax"
name = "shipwire.warehouse"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/shipwire.warehouse"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
