[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Social Media Accounts", "Cost/Free"]
org = "ballerinax"
name = "facebook.ads"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/facebook.ads"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
