[package]
license = ["Apache-2.0"]
keywords = ["Education/eLearning", "Cost/Freemium"]
org = "ballerinax"
name = "mathtools.numbers"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/mathtools.numbers"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
