[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid"]
org = "ballerinax"
name = "files.com"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/files.com"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
