[package]
license = ["Apache-2.0"]
keywords = ["Finance/Asset Management", "Cost/Paid"]
org = "ballerinax"
name = "xero.assets"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/xero.assets"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
