[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.datalake"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/azure.datalake"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
