[package]
license = ["Apache-2.0"]
keywords = ["Lifestyle & Entertainment/News & Lifestyle", "Cost/Freemium"]
org = "ballerinax"
name = "newsapi"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/newsapi"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
