[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/Website Builders", "Cost/Paid"]
org = "ballerinax"
name = "godaddy.domains"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/godaddy.domains"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
