[package]
license = ["Apache-2.0"]
keywords = ["Support/Customer Support", "Cost/Paid"]
org = "ballerinax"
name = "atspoke"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/atspoke"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
