[package]
license = ["Apache-2.0"]
keywords = ["Support/Customer Support", "Cost/Paid"]
org = "ballerinax"
name = "supportbee"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/supportbee"
version = "1.5.1"
authors = ["Ballerina"]
