[package]
license = ["Apache-2.0"]
keywords = ["Lifestyle & Entertainment/App Store", "Cost/Paid"]
org = "ballerinax"
name = "apple.appstore"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/apple.appstore"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
