[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Freemium"]
org = "ballerinax"
name = "journey.io"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/journey.io"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
