[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium"]
org = "ballerinax"
name = "insightly.custom"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/insightly.custom"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
