[package]
license = ["Apache-2.0"]
keywords = ["Business Management/ERP", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "microsoft.dynamics365businesscentral"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/microsoft.dynamics365businesscentral"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
