[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Freemium"]
org = "ballerinax"
name = "zoho.books"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/zoho.books"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
