[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/App Builders", "Cost/Paid"]
org = "ballerinax"
name = "quickbase"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/quickbase"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
