[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Paid"]
org = "ballerinax"
name = "quickbooks.online"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/quickbooks.online"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
