[package]
license = ["Apache-2.0"]
keywords = ["AI/Images", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.vision"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/googleapis.vision"
version = "1.6.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
