[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/App Builders", "Cost/Freemium"]
org = "ballerinax"
name = "powertoolsdeveloper.collections"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/powertoolsdeveloper.collections"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
