[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Security & Identity Tools", "Cost/Freemium"]
org = "ballerinax"
name = "siemens.platformcore.identitymanagement"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/siemens.platformcore.identitymanagement"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
