[package]
license = ["Apache-2.0"]
keywords = ["Finance/Asset Management", "Cost/Freemium"]
org = "ballerinax"
name = "yodlee"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/yodlee"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
