[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Paid"]
org = "ballerinax"
name = "magento.async.customer"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/magento.async.customer"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
