[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Paid", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.retail"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/googleapis.retail"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
