[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Images & Design", "Cost/Paid"]
org = "ballerinax"
name = "logoraisr"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/logoraisr"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
