[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Blogs", "Cost/Freemium"]
org = "ballerinax"
name = "medium"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/medium"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
