[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.textanalytics"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/azure.textanalytics"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
