[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Paid"]
org = "ballerinax"
name = "shipstation"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/shipstation"
version = "1.4.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
