[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Images & Design", "Cost/Free"]
org = "ballerinax"
name = "giphy"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/giphy"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
