[package]
license = ["Apache-2.0"]
keywords = ["AI/Deployment", "Vendor/Microsoft", "Cost/Paid", "Model Deployment", "Azure OpenAI"]
org = "ballerinax"
name = "azure.openai.deployment"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/azure.openai.deployment"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
