[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Server Monitoring", "Cost/Freemium"]
org = "ballerinax"
name = "bmc.truesightpresentationserver"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/bmc.truesightpresentationserver"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
