[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Freemium"]
org = "ballerinax"
name = "reckon.one"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/reckon.one"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
