[package]
license = ["Apache-2.0"]
keywords = ["Finance/Payment", "Cost/Paid"]
org = "ballerinax"
name = "nowpayments"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/nowpayments"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
