[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Freemium"]
org = "ballerinax"
name = "adobe.analytics"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/adobe.analytics"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
