[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Ads & Conversion", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.discovery"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/googleapis.discovery"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
