[package]
license = ["Apache-2.0"]
keywords = ["AI/Vector Databases", "Cost/Freemium", "Vendor/Pinecone", "Embedding Search"]
org = "ballerinax"
name = "pinecone.index"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/pinecone.index"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
