[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Documents", "Cost/Freemium"]
org = "ballerinax"
name = "docusign.rooms"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/docusign.rooms"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
