[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Task Management", "Cost/Freeemium"]
org = "ballerinax"
name = "trello"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/trello"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
