[package]
license = ["Apache-2.0"]
keywords = ["Internet of Things/Device Management", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.timeseries"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/azure.timeseries"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
